import { SimulationConfig } from '../types';

export function generateArduinoCode(config: SimulationConfig): string {
  const relayOnState = config.relayActiveMode === 'LOW' ? 'LOW' : 'HIGH';
  const relayOffState = config.relayActiveMode === 'LOW' ? 'HIGH' : 'LOW';
  const offDelayMs = config.offDelaySeconds * 1000;

  if (config.enableTempSensor) {
    return `/*
 * Smart Motion Fan Controller with Temperature Sensor Integration
 * Generated by Smart Motion Fan Controller Studio
 */

#include <DHT.h>

#define DHTPIN 4          // Temperature sensor connected to Digital Pin 4
#define DHTTYPE DHT11     // DHT 11 Temperature sensor type

// Pin Definitions
const int PIR_PIN = ${config.pirPin};    // PIR Motion Sensor connected to Digital Pin ${config.pirPin}
const int RELAY_PIN = ${config.relayPin};  // Relay Module connected to Digital Pin ${config.relayPin}
${config.enableBuzzer ? `const int BUZZER_PIN = ${config.buzzerPin}; // Optional Buzzer pin\n` : ''}
// Timer & Threshold Variables
unsigned long lastMotionTime = 0;
const unsigned long OFF_DELAY = ${offDelayMs}; // ${config.offDelaySeconds} seconds delay (in milliseconds)
const float TEMP_THRESHOLD = ${config.tempThreshold}.0; // Temperature threshold in °C

bool isFanOn = false;
DHT dht(DHTPIN, DHTTYPE);

void setup() {
  pinMode(PIR_PIN, INPUT);      // Set sensor pin as input
  pinMode(RELAY_PIN, OUTPUT);   // Set relay pin as output
  ${config.enableBuzzer ? `pinMode(BUZZER_PIN, OUTPUT);\n` : ''}
  // Relay initialization (${config.relayActiveMode === 'LOW' ? 'Active LOW: HIGH = OFF, LOW = ON' : 'Active HIGH: LOW = OFF, HIGH = ON'})
  digitalWrite(RELAY_PIN, ${relayOffState}); 
  
  Serial.begin(9600);           // Serial communication for debugging
  dht.begin();
  Serial.println("System Initialized with Temperature Guard.");
}

void loop() {
  int motionDetected = digitalRead(PIR_PIN);
  float currentTemp = dht.readTemperature();

  // Check if temperature reading is valid
  if (isnan(currentTemp)) {
    currentTemp = 25.0; // Fallback default temperature
  }

  if (motionDetected == HIGH) {
    if (currentTemp >= TEMP_THRESHOLD) {
      Serial.print("Motion detected & Temp (");
      Serial.print(currentTemp);
      Serial.println("°C) >= Threshold! Turning fan ON.");
      
      digitalWrite(RELAY_PIN, ${relayOnState}); // Turn Fan ON
      ${config.enableBuzzer ? `digitalWrite(BUZZER_PIN, HIGH); delay(50); digitalWrite(BUZZER_PIN, LOW);\n` : ''}
      isFanOn = true;
      lastMotionTime = millis();    // Reset the timer
    } else {
      Serial.print("Motion detected but Temp (");
      Serial.print(currentTemp);
      Serial.println("°C) is below threshold. Fan stays OFF.");
    }
  } else {
    // Check if the delay time has passed since last motion
    if (isFanOn && (millis() - lastMotionTime > OFF_DELAY)) {
      Serial.println("No motion for ${config.offDelaySeconds} seconds. Turning fan OFF.");
      digitalWrite(RELAY_PIN, ${relayOffState}); // Turn Fan OFF
      isFanOn = false;
    }
  }
  
  delay(500); // Small delay to prevent overload
}`;
  }

  // Base version matching user code exactly with dynamic config variables
  return `/*
 * Smart Motion Fan Controller Arduino Code
 * Automatically turns off fan when no motion is detected for ${config.offDelaySeconds} seconds
 */

// Pin Definitions
const int PIR_PIN = ${config.pirPin};    // PIR Motion Sensor connected to Digital Pin ${config.pirPin}
const int RELAY_PIN = ${config.relayPin};  // Relay Module connected to Digital Pin ${config.relayPin}
${config.enableBuzzer ? `const int BUZZER_PIN = ${config.buzzerPin}; // Buzzer Notification Pin\n` : ''}
// Timer Variables
unsigned long lastMotionTime = 0;
const unsigned long OFF_DELAY = ${offDelayMs}; // ${config.offDelaySeconds} seconds delay (in milliseconds) before turning off
bool isFanOn = false;

void setup() {
  pinMode(PIR_PIN, INPUT);      // Set sensor pin as input
  pinMode(RELAY_PIN, OUTPUT);   // Set relay pin as output
  ${config.enableBuzzer ? `pinMode(BUZZER_PIN, OUTPUT);\n` : ''}
  // Most relay modules are active LOW (${config.relayActiveMode === 'LOW' ? 'LOW = ON, HIGH = OFF' : 'HIGH = ON, LOW = OFF'})
  digitalWrite(RELAY_PIN, ${relayOffState}); 
  Serial.begin(9600);           // Serial communication for debugging
  Serial.println("Smart Motion Fan Controller Ready.");
}

void loop() {
  int motionDetected = digitalRead(PIR_PIN);

  if (motionDetected == HIGH) {
    Serial.println("Motion detected! Turning fan ON.");
    digitalWrite(RELAY_PIN, ${relayOnState}); // Turn Fan ON
    ${config.enableBuzzer ? `digitalWrite(BUZZER_PIN, HIGH); delay(50); digitalWrite(BUZZER_PIN, LOW);\n` : ''}
    isFanOn = true;
    lastMotionTime = millis();    // Reset the timer
  } else {
    // Check if the delay time has passed since last motion
    if (isFanOn && (millis() - lastMotionTime > OFF_DELAY)) {
      Serial.println("No motion for ${config.offDelaySeconds} seconds. Turning fan OFF.");
      digitalWrite(RELAY_PIN, ${relayOffState}); // Turn Fan OFF
      isFanOn = false;
    }
  }
  
  delay(500); // Small delay to prevent overload
}`;
}
